version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-main
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    environment:
      - JAVA_OPS=-Xmx1g
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /volume1/docker/jenkins:/var/jenkins_home
    restart: always