spring:
  application:
    name: module-web-api
  profiles:
    active: development # development // production
  servlet:
    multipart:
      enabled: true # Enable multipart uploads
      max-file-size: 1MB # 파일 최대 크기
      max-request-size: 10MB # 요청 최대 크기

springdoc:
  version: '@project.version@'
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none
  paths-to-match:
    - /api/**
    - /open-api/**