server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: info
    root: info
    com.zaxxer.hikari.pool.HikariPool: debug

token:
  secret:
    key: BongProJWTSecretTokenValue1!2@3#4$
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12

spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3307/spring_practice?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: everyplay1!
    hikari :
      connection-timeout: 3000
      validation-timeout: 3000
      minimum-idle: 5
      max-lifetime: 240000
      maximum-pool-size: 20